spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: Seat_Planner
  activemq:
    in-memory: true
    pooled: false
  profiles: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

optaplanner:
  solver:
    move-thread-count: AUTO
    termination:
      unimproved-spent-limit: 500ms
      best-score-limit: 0hard/0soft
      spent-limit: 5s

ui:
  url: http://localhost:8080